# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           http://localhost:4000 

# Setup
title:               Bestimever
tagline:             '这是最好的时代，也是最坏的时代'
description:         '发现，生活的另一面'
url:                 http://watermelon92.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dylan
  url:               https://twitter.com/TRealize
  email:             tobestshow@gmail.com

# Custom vars
version:             1.0.0
